server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/mydb
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      generate-ddl-auto: validate